version: '3.8'

services:
  app:
    build: .
    ports:
      - "8090:8090"
    environment:
      # Ensure your application (e.g., in config/settings.py) can read these
      # Example: DATABASE_URL: postgresql://user:password@postgres:5432/mydatabase
      # Example: MYSQL_URL: mysql+mysqlconnector://user:password@mysql:3306/mydatabase
      # Example: MONGO_URL: mongodb://root:secret@mongo:27017/
      PYTHONUNBUFFERED: 1 # For real-time logging
      PYTHONDONTWRITEBYTECODE: 1
      # Add other necessary environment variables for your app here
      # e.g., API_KEY: your_api_key
    depends_on:
      - postgres
      - mysql
      - mongo
    volumes:
      - .:/app # Mounts the current directory on the host to /app in the container for development hot-reloading

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  mysql_data:
  mongo_data:
  pgadmin_data:
